# SweetDependency project configuration file
# You can adjust your custom configuration to your liking here
# You can visit https://github.com/HighCapable/SweetDependency for more help
#
# SweetDependency 项目配置文件
# 你可以在这里调整你喜欢的自定义配置
# 你可以前往 https://github.com/HighCapable/SweetDependency 以获得更多帮助

preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  maven-xposed:
    url: https://api.xposed.info/
  jitpack:
    url: https://jitpack.io

plugins:
  com.android.application:
    version: 8.4.1
  org.jetbrains.kotlin.android:
    version: 1.9.24
  com.google.devtools.ksp:
    version: 1.9.24-1.0.20

libraries:
  de.robv.android.xposed:
    api:
      version: 82
  com.highcapable.yukihookapi:
    api:
      version: 1.2.0
    ksp-xposed:
      version: 1.2.0
  androidx.palette:
    palette-ktx:
      version: 1.0.0
  androidx.compose.material3:
    material3:
      version: 1.2.1
  org.jetbrains.kotlinx:
    kotlinx-coroutines-android:
      version: 1.8.1
  androidx.annotation:
    annotation:
      version: 1.8.0